spring:

  datasource:

    url: jdbc:mysql://localhost:3306/spring_crud
    username: root
    password: 123456


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect













